### ISSUE TITLE
getting cy.task('gmail:get-messages') timed out after waiting 60000ms.

### ISSUE THREAD

**Issue by NilukaSripalim** [levz0r/gmail-tester#35] opened 2020-04-10 10:38 UTC
Followed git instruction , 
unable to get mail, 
getting cy.task('gmail:get-messages') timed out after waiting 60000ms.

**Comment by levz0r** [comment] 2020-05-12 15:19
Duplicate of #17.

**Closed by levz0r** 2020-05-12 15:19 UTC

**Comment by FredMottey-expel** [comment] 2020-05-17 20:19
Hi, is there any resolution to this? getting the same error actually
